version: '3'

vars:
  VERSION: v0.0.2

tasks:
  install:
    desc: "Install dependencies"
    cmds:
      - go mod tidy

  build:
    desc: "Build the CLI tool"
    cmds:
      - mkdir -p bin
      - go build -o bin/passgen

  run:
    desc: "Run the CLI tool with default options"
    cmds:
      - bin/passgen generate

  test:
    desc: "Run unit tests"
    cmds:
      - go test ./... -v -cover

  docker-build:
    desc: "Build the Docker image"
    cmds:
      - docker build -t dekuyo/passgen:{{.VERSION}} .

  docker-run:
    desc: "Run the CLI tool in a Docker container"
    cmds:
      - docker run --rm dekuyo/passgen:{{.VERSION}} generate -l 12 -c false -t 10 -n 3 -o json

  docker-push:
    desc: "Push the Docker image to Docker Hub"
    cmds:
      - docker push dekuyo/passgen:{{.VERSION}}

  clean:
    desc: "Clean up build files"
    cmds:
      - rm -rf bin

  help:
    desc: "Show help for Taskfile commands"
    cmds:
      - task --list
